project_name: nezha-agent

version: 2

snapshot:
  version_template: "{{ .Version }}"

builds:
  - id: universal
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}}
    goos:
      - linux
    goarch:
      - amd64
    goamd64: 
      - v3
      - v2
    main: ./cmd/agent
    binary: nezha-agent

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-{{ .Amd64 }}"
    format: tar.gz
